

# Database
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres.sujbdwubejoabesoykat
spring.datasource.password=V5UDkp4w%U$vxU.
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Hibernate PostgreSQL properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=true



spring.jackson.property-naming-strategy=SNAKE_CASE

# JWT: Security configuration
jwt.secret=MealPlannerSuperSecretKeyMustBeAtLeast256BitsLongForHS256Algorithm!!
jwt.expiration-ms=86400000


corsAllowedOrigins=http://localhost:5173
server.port=8080
